
service: ecr-testing

frameworkVersion: '2'

provider:
  name: aws
  lambdaHashingVersion: 20201221
  ecr:
    images:
      appimage:
        path: ./

functions:
  func1:
    image:
      name: appimage
      command:
        - app.handler
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - http:
          path: /hello
          method: GET
  func2:
    image:
      name: appimage
      command:
        - app.handler2
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - http:
          path: /goodbye
          method: GET
  
